### ISSUE TITLE
Build failed with GCC 7.3.0

### ISSUE THREAD

**Issue by 9a8t9m8** [Kampbell/qfsm#1]
Compiling with GCC 7.3.0 aborted stating the following error:
> /qfsm/src/FileIO.cpp:1620:12: error: cannot convert ‘bool’ to ‘Project*’ in return
     return FALSE;

It seems like this occurs at least since GCC 6.0 as issued [here](https://github.com/rdiankov/collada-dom/issues/22) before due to more strict type conversion.

**Comment by zosrothko** [comment]
Fixed
